# Generated by Django 3.1.3 on 2020-11-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('token', models.CharField(max_length=36, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exception', models.TextField(default='')),
                ('version', models.IntegerField(default=2)),
                ('started', models.DateTimeField(null=True)),
                ('stoped', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
